import NoveltyTheory.Core.GenerativeSystem
import NoveltyTheory.Core.Phase
import NoveltyTheory.Core.ExplanatoryRegime
import NoveltyTheory.Core.Reduction
import NoveltyTheory.Core.Conservative
import NoveltyTheory.Core.ParadigmShift
import NoveltyTheory.Core.Tower
import NoveltyTheory.Core.ReducerEnumeration
import NoveltyTheory.Core.Explains
import NoveltyTheory.Core.Sentence
import NoveltyTheory.Core.NatPhaseTag
import NoveltyTheory.Core.SentenceSemantics
import NoveltyTheory.Core.SentenceRegime
import NoveltyTheory.Core.Expressibility
import NoveltyTheory.Core.GeneratorTruth
import NoveltyTheory.Core.Organization
import NoveltyTheory.Core.SimulationVersusExplanationAbstract
import NoveltyTheory.Foundation.Trajectory
import NoveltyTheory.Foundation.ConservativeHistory
import NoveltyTheory.Foundation.SentenceFacts
import NoveltyTheory.Foundation.ProvabilityFacts
import NoveltyTheory.Foundation.UpwardNecessity
import NoveltyTheory.Foundation.StructuralGeneratorSentence
import NoveltyTheory.Foundation.AscentRegime
import NoveltyTheory.Foundation.RichSentenceSyntax
import NoveltyTheory.Foundation.InitialTagProvability
import NoveltyTheory.Foundation.StageModality
import NoveltyTheory.Models.SignatureTower
import NoveltyTheory.Models.InvariantTower
import NoveltyTheory.Models.SentenceProvability
import NoveltyTheory.Models.StratifiedSentenceModel
import NoveltyTheory.Models.StratifiedFinality
import NoveltyTheory.Models.RetroStructuralTruth
import NoveltyTheory.Models.BoundedRegimeDiagonal
import NoveltyTheory.Models.ReducerDiagonal
import NoveltyTheory.Models.DupRegimeTower
import NoveltyTheory.Models.RegimeFamilyObstruction
import NoveltyTheory.Models.CausalExplanatoryOrders
import NoveltyTheory.Models.GenCertPhase
import NoveltyTheory.Core.ExplanatoryOrder
import NoveltyTheory.Models.SimulationVersusExplanation
import NoveltyTheory.Ridge.ShiftWitness
import NoveltyTheory.Ridge.DiagonalNat
import NoveltyTheory.Ridge.InterfaceAlignment
import NoveltyTheory.Ridge.SignatureAdmissibleBundle
import NoveltyTheory.Summits.CausalExplanatorySeparation
import NoveltyTheory.Summits.SummitPackages
import NoveltyTheory.Summits.OrganizationSummit
import NoveltyTheory.Summits.NecessityStratifiedFinalitySummit
import NoveltyTheory.Summits.StrongRetroCausationSummit
import NoveltyTheory.Summits.GeneratorTruthRidge
import NoveltyTheory.Summits.UnfoldingNecessitySummit
import NoveltyTheory.Summits.SimulationVersusExplanationAbstractSummit
import NoveltyTheory.Summits.CrownIteratedAscentSummit
import NoveltyTheory.Summits.OrganizationFrontierSummit

/-!
# NoveltyTheory — library root (`SPEC_003_RCT`)

Imports **Core → Foundation → Models → Ridge → Summits**. Add new modules beside this file and
extend the import list in the same change.
-/
